Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "ubuntu/focal64"
    db01.vm.box_version = "20240821.0.1"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.50.30"
    db01.vm.network "public_network", ip: "192.168.1.30"
    db01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end

  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "ubuntu/focal64"
    mc01.vm.box_version = "20240821.0.1"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.50.31"
    mc01.vm.network "public_network", ip: "192.168.1.31"
    mc01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
  end
  
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "ubuntu/focal64"
    rmq01.vm.box_version = "20240821.0.1"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.50.32"
    rmq01.vm.network "public_network", ip: "192.168.1.32"
    rmq01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
  end
  
### tomcat vm ###
   config.vm.define "app01" do |app01|
    app01.vm.box = "ubuntu/focal64"
    app01.vm.box_version = "20240821.0.1"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.50.33"
    app01.vm.network "public_network", ip: "192.168.1.33"
    app01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
   end
   
  
### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/focal64"
    web01.vm.box_version = "20240821.0.1"
    web01.vm.hostname = "web01"
  web01.vm.network "private_network", ip: "192.168.50.34"
  web01.vm.network "public_network", ip: "192.168.1.34"
  web01.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
   end
end
  
end
